name: Create autoscript package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - master
jobs:
  Package_Autoscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: List changed directories
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v40
        with:
          dir_names: "true"
        run: |
          for dir in in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            echo "$dir was changed"
