name: Create autoscript package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - master
jobs:
  Check_For_Changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Get changed directories
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v40
        with:
          dir_names: "true"
      - name: List changed directories
        run: |
          for dir in in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            echo "$dir was changed"
            echo "DIRNAME=$dir" >> $GITHUB_ENV
            echo "set ${{ DIRNAME }}"
            echo "${{ steps.changed-files-dir-names.outputs.any_modified }}"
          done
      - name: create zip artifact
        if: ${{ steps.changed-files-dir-names.outputs.any_modified }} == 'true'
        uses: ksm2/archive-action@v1
        with:
          format: "tar.gz"
          root-directory: ${{ $DIRNAME }}
          name: ${{ DIRNAME }}
          include: "*.(json|tcl)"
